package User_Interface_Layer;

import Business_Layer.Property;
import Control_Layer.UpdateController;

import javax.swing.*;
import java.util.ArrayList;
import javax.swing.JFrame;

public class UpdateForm extends InteractionForm{

    javax.swing.JFrame f; // The JFrame object.
    Property chosenProperty; // The Property object chosen to be updated.


    /**
     * Creates new form UpdateForm
     */
    public UpdateForm(Property p) {
        myControllers.add(new UpdateController());
        chosenProperty = p;
        changeStatus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void changeStatus() {
        f = new javax.swing.JFrame();
        f.setVisible(true);
        header1 = new javax.swing.JLabel();
        header2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        addressLabel = new javax.swing.JLabel();
        propertyAddressLabel = new javax.swing.JLabel();
        quadrantLabel = new javax.swing.JLabel();
        propertyQuadrantLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        propertyTypeLabel = new javax.swing.JLabel();
        furnishedLabel = new javax.swing.JLabel();
        propertyFurnishedLabel = new javax.swing.JLabel();
        numBathroomsLabel = new javax.swing.JLabel();
        propertyNumBathroomsLabel = new javax.swing.JLabel();
        numBedroomsLabel = new javax.swing.JLabel();
        propertyNumBedroomsLabel = new javax.swing.JLabel();
        datePostedLabel = new javax.swing.JLabel();
        propertyDatePostedLabel = new javax.swing.JLabel();
        dateExpiryLabel = new javax.swing.JLabel();
        propertyDateExpiryLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        propertyStatusLabel = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        header3 = new javax.swing.JLabel();
        statusList = new javax.swing.JComboBox<>();

        f.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header1.setText("Choose a new status to update to.");

        header2.setText("Detailed Property Information:");

        addressLabel.setText("Address: ");

        propertyAddressLabel.setText("jLabel4");

        quadrantLabel.setText("Quadrant:");

        propertyQuadrantLabel.setText("jLabel6");

        typeLabel.setText("Type:");

        propertyTypeLabel.setText("jLabel8");

        furnishedLabel.setText("Furnished:");

        propertyFurnishedLabel.setText("jLabel10");

        numBathroomsLabel.setText("Number of bathrooms:");

        propertyNumBathroomsLabel.setText("jLabel12");

        numBedroomsLabel.setText("Number of bedrooms:");

        propertyNumBedroomsLabel.setText("jLabel14");

        datePostedLabel.setText("Date Posted:");

        propertyDatePostedLabel.setText("jLabel16");

        dateExpiryLabel.setText("Date of Expiry:");

        propertyDateExpiryLabel.setText("jLabel18");

        statusLabel.setText("Current Status:");

        propertyStatusLabel.setText("jLabel20");

        updateButton.setForeground(new java.awt.Color(0, 255, 0));
        updateButton.setText("CONFIRM UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boolean success = true;
                String newStatus = statusList.getSelectedItem().toString();
                if (chosenProperty.getStatus().equals("Cancelled")) success = false;
                updateButtonActionPerformed(evt, success, newStatus);
            }
        });

        backButton.setText("<<");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        header3.setText("Choose a new status:");

        statusList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        statusList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Cancelled", "Rented", "Suspended" }));
        String furn = "Y";
        if (!chosenProperty.isFurnished()) furn = "N";
        propertyAddressLabel.setText(chosenProperty.getAddress());
        propertyQuadrantLabel.setText(chosenProperty.getQuadrant());
        propertyFurnishedLabel.setText(furn);
        propertyStatusLabel.setText(chosenProperty.getStatus());
        propertyNumBathroomsLabel.setText(String.valueOf(chosenProperty.getNumBathrooms()));
        propertyNumBedroomsLabel.setText(String.valueOf(chosenProperty.getNumBedrooms()));
        propertyDateExpiryLabel.setText(chosenProperty.getExpDate());
        propertyDatePostedLabel.setText(chosenProperty.getPostedDate());
        propertyTypeLabel.setText(chosenProperty.getType());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(f.getContentPane());
        f.getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(111, 111, 111)
                                                                .addComponent(header1))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(header2))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(addressLabel)
                                                                        .addComponent(quadrantLabel)
                                                                        .addComponent(typeLabel)
                                                                        .addComponent(furnishedLabel)
                                                                        .addComponent(numBathroomsLabel)
                                                                        .addComponent(numBedroomsLabel)
                                                                        .addComponent(datePostedLabel)
                                                                        .addComponent(dateExpiryLabel)
                                                                        .addComponent(statusLabel))
                                                                .addGap(147, 147, 147)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(propertyStatusLabel)
                                                                        .addComponent(propertyDateExpiryLabel)
                                                                        .addComponent(propertyDatePostedLabel)
                                                                        .addComponent(propertyNumBedroomsLabel)
                                                                        .addComponent(propertyNumBathroomsLabel)
                                                                        .addComponent(propertyFurnishedLabel)
                                                                        .addComponent(propertyTypeLabel)
                                                                        .addComponent(propertyQuadrantLabel)
                                                                        .addComponent(propertyAddressLabel))))
                                                .addGap(0, 85, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(backButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(header3)
                                                        .addComponent(updateButton)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addComponent(statusList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(header1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(header2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addressLabel)
                                        .addComponent(propertyAddressLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(quadrantLabel)
                                        .addComponent(propertyQuadrantLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(typeLabel)
                                        .addComponent(propertyTypeLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(furnishedLabel)
                                        .addComponent(propertyFurnishedLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(numBathroomsLabel)
                                        .addComponent(propertyNumBathroomsLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(numBedroomsLabel)
                                        .addComponent(propertyNumBedroomsLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(datePostedLabel)
                                        .addComponent(propertyDatePostedLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(dateExpiryLabel)
                                        .addComponent(propertyDateExpiryLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(statusLabel)
                                        .addComponent(propertyStatusLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(header3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(statusList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(updateButton)
                                        .addComponent(backButton))
                                .addContainerGap())
        );

        f.pack();
    }// </editor-fold>

    /* If user clicks update, send the new updated property to controller and take user back to home page */
    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt, boolean success, String newStatus) {
        if (!success)
        {
            JOptionPane.showMessageDialog(f, "You cannot update a property that has been cancelled.",
                    "INVALID SELECTION", JOptionPane.ERROR_MESSAGE);
        } else {
            chosenProperty.setType(newStatus);
            /* Send the new property to the controller for it to be updated. */
            ((UpdateController)(myControllers.get(0))).forwardPropertyStatus(chosenProperty);
            JOptionPane.showMessageDialog(null, "Your property has successfully been updated!", "Update successful",
                    1);
            f.dispose();
            new GUIHomePage().performStrategy();
        }
    }

    /* If user presses back button, take them to the property selection page*/
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {
        f.dispose();
        new PropertyForm().browseProperties();
    }


    // Variables declaration - do not modify
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel dateExpiryLabel;
    private javax.swing.JLabel datePostedLabel;
    private javax.swing.JLabel furnishedLabel;
    private javax.swing.JLabel header1;
    private javax.swing.JLabel header2;
    private javax.swing.JLabel header3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel numBathroomsLabel;
    private javax.swing.JLabel numBedroomsLabel;
    private javax.swing.JLabel propertyAddressLabel;
    private javax.swing.JLabel propertyDateExpiryLabel;
    private javax.swing.JLabel propertyDatePostedLabel;
    private javax.swing.JLabel propertyFurnishedLabel;
    private javax.swing.JLabel propertyNumBathroomsLabel;
    private javax.swing.JLabel propertyNumBedroomsLabel;
    private javax.swing.JLabel propertyQuadrantLabel;
    private javax.swing.JLabel propertyStatusLabel;
    private javax.swing.JLabel propertyTypeLabel;
    private javax.swing.JLabel quadrantLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JComboBox<String> statusList;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration
}